apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - security/
  - helm-argo/
  - operators/
  - acm-cluster-configs/

namespace: dmte-acm-samples

# resources:
#   - acm-placements/

