apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-helm-repos
  namespace: openshift-gitops
spec:
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'