apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-cm-one
  namespace: openshift-devspaces
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
data:
  ca.crt: |-
    # SMBC-Subordinate-CA1-G2
    -----BEGIN CERTIFICATE-----
    MIIGUzCCBTugAwIBAgITJwAAAATALpHMpnr7JAAAAAAABDANBgkqhkiG9w0BAQsF
    ADBKMRMwEQYKCZImiZPyLGQBGRYDY29tMRkwFwYKCZImiZPyLGQBGRYJc21iY2dy
    b3VwMRgwFgYDVQQDEw9TTUJDLVJvb3QtQ0EtRzIwHhcNMTgwMjA2MTcxNzM1WhcN
    MjgwMjA0MTcxNzM1WjB2MRMwEQYKCZImiZPyLGQBGRYDY29tMRkwFwYKCZImiZPy
    LGQBGRYJc21iY2dyb3VwMSIwIAYDVQQLExlTTUJDIEluZm9ybWF0aW9uIFNlY3Vy
    aXR5MSAwHgYDVQQDExdTTUJDLVN1Ym9yZGluYXRlLUNBMS1HMjCCASIwDQYJKoZI
    hvcNAQEBBQADggEPADCCAQoCggEBALdYjnvVGLq8198b5LmZZ/UhMFvgHZkpZ8Nd
    bhguxz1TRFQVgCmxflaDvFiMKExwBbZ2VQhN/mRd+uRZpjl+uHF0UjTSdsloOwYG
    4ahzWwDg5b4Wve1W6icZ3OlL3fZFKq8xFPy7w2dK3dJy2LTd2ixEtJl4qN2jBYR4
    1nX5ylWTJ47fLBwjd5Z9dvrF49PIgk9MXl/7NM0OPS2IwzHkzAFBNyr4Pc6qRIz1
    w5c+PBCdlpeumRgFN4H8hijBu6JGpdq+miqdNY72kF8bwWKNgrypdHFDIQO88F5b
    uwMw9b5GUVaPJ5usy29KYFCR7mIwK5EXMSNLnFpj39/riyuq/SkCAwEAAaOCAwQw
    ggMAMA4GA1UdDwEB/wQEAwIBhjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQW
    BBQm4Bi2MInA+KfIDnHKZVQ+TG5njzAfBgNVHSMEGDAWgBQLWAa5ETSypll7X+y4
    ilhrswA75zCCAUsGA1UdHwSCAUIwggE+MIIBOqCCATagggEyhoG/bGRhcDovLy9D
    Tj1TTUJDLVJvb3QtQ0EtRzIsQ049TkpDVkNBUk9PVFBSMDEsQ049Q0RQLENOPVB1
    YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRp
    b24sREM9c21iY2dyb3VwLERDPWNvbT9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0
    P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnSGMmh0dHA6Ly93
    d3cuanJpLWFtZXJpY2EuY29tL0NEUC9TTUJDLVJvb3QtQ0EtRzIuY3JshjpodHRw
    Oi8vQ2VydERpc3RQb2ludC5zbWJjZ3JvdXAuY29tL3BraS9TTUJDLVJvb3QtQ0Et
    RzIuY3JsMIIBCwYIKwYBBQUHAQEEgf4wgfswgbAGCCsGAQUFBzAChoGjbGRhcDov
    Ly9DTj1TTUJDLVJvb3QtQ0EtRzIsQ049QUlBLENOPVB1YmxpYyUyMEtleSUyMFNl
    cnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9c21iY2dyb3Vw
    LERDPWNvbT9jQUNlcnRpZmljYXRlP2Jhc2U/b2JqZWN0Q2xhc3M9Y2VydGlmaWNh
    dGlvbkF1dGhvcml0eTBGBggrBgEFBQcwAoY6aHR0cDovL0NlcnREaXN0UG9pbnQu
    c21iY2dyb3VwLmNvbS9wa2kvU01CQy1Sb290LUNBLUcyLmNydDA8BgkrBgEEAYI3
    FQcELzAtBiUrBgEEAYI3FQix0GKH7E2GyZMFgqSEMIHtuXaBHoW0+VqE3bUTAgFk
    AgEEMA0GCSqGSIb3DQEBCwUAA4IBAQBL1CSGPyo890tDL9XPaIH42VQ8uB2KzvyN
    OLMrrRfmECuJlQKCUhKhWgMdlRLFEsLEANQi5f4jMWIaCWffWccJEGN2C5od8xte
    YVHaXgMnI86jv9hFx8eYePdM+YUNpf7SdOsmpyLQxPaZGbw3U53xNWxc8ZUBy0wV
    eHOn88AxSq3JuGkdOXfG0sHzO8rxb4F4lhenqPHRAhcgzlEg2jANWdmLBDvQkolP
    b51BZWwzMdLm1zQS1jtOjUAFwf6jLqGaaOD9eFu9wGsAUwlUlq79096TQqrPcS3x
    PIjRl1urG+JUcLP0sz5k82hqovsruIRRbykd5DiE5n7chZieXHGF
    -----END CERTIFICATE-----
  
    # SMBC-Root-CA-G2
    -----BEGIN CERTIFICATE-----
    MIIEHDCCAwSgAwIBAgIQXCngoMKDHZFLjZnFoLkj3TANBgkqhkiG9w0BAQsFADBK
    MRMwEQYKCZImiZPyLGQBGRYDY29tMRkwFwYKCZImiZPyLGQBGRYJc21iY2dyb3Vw
    MRgwFgYDVQQDEw9TTUJDLVJvb3QtQ0EtRzIwHhcNMTgwMjA2MTYzMDQ5WhcNMzgw
    MjA2MTY0MDQ0WjBKMRMwEQYKCZImiZPyLGQBGRYDY29tMRkwFwYKCZImiZPyLGQB
    GRYJc21iY2dyb3VwMRgwFgYDVQQDEw9TTUJDLVJvb3QtQ0EtRzIwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQC1Br0grh6BBU4ysoHBmWgmOy72FLNtzDm1
    g9YLF4znkSdfdYi96kWdbxvFTWLoBomDn9GA7Dn63wR9GZ2nx9R+MeBfiZ9p5Q8d
    0j2/sO2tGKV8pzAx/athAKN0ReYeZCrjA/twHteT449q5Xs54CVK8kSNBy54l1mT
    hoDJRFvBPidg9onedBuecWtuWroUJFINeUUNgUouKayDEBmSby3MDxoT+9lIencQ
    vJN72DnCjCQVWN2R6ii5uQIOn8AfMO1S4uV/Kahf7AHkwRM23NI+ZkISzWrFp26i
    Kvk01wp6QRtIdTVU+LWQ1AlUM9MS1Ew8T/lNbPOWq7HhFazqxnflAgMBAAGjgf0w
    gfowEwYJKwYBBAGCNxQCBAYeBABDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQF
    MAMBAf8wHQYDVR0OBBYEFAtYBrkRNLKmWXtf7LiKWGuzADvnMBAGCSsGAQQBgjcV
    AQQDAgEAMIGTBgNVHSAEgYswgYgwgYUGCCoDBIsvQ1kFMHkwOgYIKwYBBQUHAgIw
    Lh4sAEwAZQBnAGEAbAAgAFAAbwBsAGkAYwB5ACAAUwB0AGEAdABlAG0AZQBuAHQw
    OwYIKwYBBQUHAgEWL2h0dHA6Ly9DZXJ0RGlzdFBvaW50LnNtYmNncm91cC5jb20v
    cGtpL2Nwcy50eHQAMA0GCSqGSIb3DQEBCwUAA4IBAQB+W5SD59t9KFQNiSMWgNEh
    YU27AlwGKLxzhBigDwO+/ojo89LP8H+XbRCA5Z9qa7G80jhtsxpNNvkmMXLQ1pO5
    hiyq02q3RJDmLbnWu4IYxwfmwhrQtBECpfx+ZMrhTFsCbmaUaU3Fz87VPO+WN9Ii
    euyyJyD15jjYWeX9QGouV0OFTRctGjUKcYNnEOQpPNKXbH0BR3vsYJR+jLcbMTr8
    YHzWT0AeLvgjEK2c/IrtZ7KCX8g2Mw2Evs6lroPvXKnKYnt5NaVwbk5PC4SOh2zj
    WxJAlIozip0uhIN3QThUs2wyYvmgggRXxSI+LDwsMNKZQC+bJl+STjHo9jYvcyCC
    -----END CERTIFICATE-----
  
    # Entrust Intermediate
    -----BEGIN CERTIFICATE-----
    MIIFDjCCA/agAwIBAgIMDulMwwAAAABR03eFMA0GCSqGSIb3DQEBCwUAMIG+MQsw
    CQYDVQQGEwJVUzEWMBQGA1UEChMNRW50cnVzdCwgSW5jLjEoMCYGA1UECxMfU2Vl
    IHd3dy5lbnRydXN0Lm5ldC9sZWdhbC10ZXJtczE5MDcGA1UECxMwKGMpIDIwMDkg
    RW50cnVzdCwgSW5jLiAtIGZvciBhdXRob3JpemVkIHVzZSBvbmx5MTIwMAYDVQQD
    EylFbnRydXN0IFJvb3QgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkgLSBHMjAeFw0x
    NTEwMDUxOTEzNTZaFw0zMDEyMDUxOTQzNTZaMIG6MQswCQYDVQQGEwJVUzEWMBQG
    A1UEChMNRW50cnVzdCwgSW5jLjEoMCYGA1UECxMfU2VlIHd3dy5lbnRydXN0Lm5l
    dC9sZWdhbC10ZXJtczE5MDcGA1UECxMwKGMpIDIwMTIgRW50cnVzdCwgSW5jLiAt
    IGZvciBhdXRob3JpemVkIHVzZSBvbmx5MS4wLAYDVQQDEyVFbnRydXN0IENlcnRp
    ZmljYXRpb24gQXV0aG9yaXR5IC0gTDFLMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
    MIIBCgKCAQEA2j+W0E25L0Tn2zlem1DuXKVh2kFnUwmqAJqOV38pa9vH4SEkqjrQ
    jUcj0u1yFvCRIdJdt7hLqIOPt5EyaM/OJZMssn2XyP7BtBe6CZ4DkJN7fEmDImiK
    m95HwzGYei59QAvS7z7Tsoyqj0ip/wDoKVgG97aTWpRzJiatWA7lQrjV6nN5ZGhT
    JbiEz5R6rgZFDKNrTdDGvuoYpDbwkrK6HIiPOlJ/915tgxyd8B/lw9bdpXiSPbBt
    LOrJz5RBGXFEaLpHPATpXbo+8DX3Fbae8i4VHj9HyMg4p3NFXU2wO7GOFyk36t0F
    ASK7lDYqjVs1/lMZLwhGwSqzGmIdTivZGwIDAQABo4IBDDCCAQgwDgYDVR0PAQH/
    BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwMwYIKwYBBQUHAQEEJzAlMCMGCCsG
    AQUFBzABhhdodHRwOi8vb2NzcC5lbnRydXN0Lm5ldDAwBgNVHR8EKTAnMCWgI6Ah
    hh9odHRwOi8vY3JsLmVudHJ1c3QubmV0L2cyY2EuY3JsMDsGA1UdIAQ0MDIwMAYE
    VR0gADAoMCYGCCsGAQUFBwIBFhpodHRwOi8vd3d3LmVudHJ1c3QubmV0L3JwYTAd
    BgNVHQ4EFgQUgqJwdN28Uz/Pe9T3zX+nYMYKTL8wHwYDVR0jBBgwFoAUanImetAe
    733nO2lR1GyNn5ASZqswDQYJKoZIhvcNAQELBQADggEBADnVjpiDYcgsY9NwHRkw
    y/YJrMxp1cncN0HyMg/vdMNY9ngnCTQIlZIv19+4o/0OgemknNM/TWgrFTEKFcxS
    BJPok1DD2bHi4Wi3Ogl08TRYCj93mEC45mj/XeTIRsXsgdfJghhcg85x2Ly/rJkC
    k9uUmITSnKa1/ly78EqvIazCP0kkZ9Yujs+szGQVGHLlbHfTUqi53Y2sAEo1GdRv
    c6N172tkw+CNgxKhiucOhk3YtCAbvmqljEtoZuMrx1gL+1YQ1JH7HdMxWBCMRON1
    exCdtTix9qrKgWRs6PLigVWXUX/hwidQosk8WwBD9lu51aX8/wdQQGcHsFXwt35u
    Lcw=
    -----END CERTIFICATE-----
  
    # Entrust Root Certification Authority - G2
    -----BEGIN CERTIFICATE-----
    MIIEPjCCAyagAwIBAgIESlOMKDANBgkqhkiG9w0BAQsFADCBvjELMAkGA1UEBhMC
    VVMxFjAUBgNVBAoTDUVudHJ1c3QsIEluYy4xKDAmBgNVBAsTH1NlZSB3d3cuZW50
    cnVzdC5uZXQvbGVnYWwtdGVybXMxOTA3BgNVBAsTMChjKSAyMDA5IEVudHJ1c3Qs
    IEluYy4gLSBmb3IgYXV0aG9yaXplZCB1c2Ugb25seTEyMDAGA1UEAxMpRW50cnVz
    dCBSb290IENlcnRpZmljYXRpb24gQXV0aG9yaXR5IC0gRzIwHhcNMDkwNzA3MTcy
    NTU0WhcNMzAxMjA3MTc1NTU0WjCBvjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUVu
    dHJ1c3QsIEluYy4xKDAmBgNVBAsTH1NlZSB3d3cuZW50cnVzdC5uZXQvbGVnYWwt
    dGVybXMxOTA3BgNVBAsTMChjKSAyMDA5IEVudHJ1c3QsIEluYy4gLSBmb3IgYXV0
    aG9yaXplZCB1c2Ugb25seTEyMDAGA1UEAxMpRW50cnVzdCBSb290IENlcnRpZmlj
    YXRpb24gQXV0aG9yaXR5IC0gRzIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQC6hLZy254Ma+KZ6TABp3bqMriVQRrJ2mFOWHLP/vaCeb9zYQYKpSfYs1/T
    RU4cctZOMvJyig/3gxnQaoCAAEUesMfnmr8SVycco2gvCoe9amsOXmXzHHfV1IWN
    cCG0szLni6LVhjkCsbjSR87kyUnEO6fe+1R9V77w6G7CebI6C1XiUJgWMhNcL3hW
    wcKUs/Ja5CeanyTXxuzQmyWC48zCxEXFjJd6BmsqEZ+pCm5IO2/b1BEZQvePB7/1
    U1+cPvQXLOZprE4yTGJ36rfo5bs0vBmLrpxR57d+tVOxMyLlbc9wPBr64ptntoP0
    jaWvYkxN4FisZDQSA/i2jZRjJKRxAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRqciZ60B7vfec7aVHUbI2fkBJmqzAN
    BgkqhkiG9w0BAQsFAAOCAQEAeZ8dlsa2eT8ijYfThwMEYGprmi5ZiXMRrEPR9RP/
    jTkrwPK9T3CMqS/qF8QLVJ7UG5aYMzyorWKiAHarWWluBh1+xLlEjZivEtRh2woZ
    Rkfz6/djwUAFQKXSt/S1mja/qYh2iARVBCuch38aNzx+LaUa2NSJXsq9rD1s2G2v
    1fN2D807iDginWyTmsQ9v4IbZT+mD12q/OWyFcq1rca8PdCE6OoGcrBNOTJ4vz4R
    nAuknZoh8/CbCzB428Hch0P+vGOaysXCHMnHjf87ElgI5rY97HosTvuDls4MPGmH
    VHOkc8KT/1EQrBVUAdj8BbGJoX90g5pJ19xOe4pIb4tF9g==
    -----END CERTIFICATE-----