apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splunk-otel-collector
  namespace: openshift-gitops
spec:
  project: cluster-helm-repos

  destination:
    name: ''
    namespace: 'otel'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'helm-charts/splunk-otel-collector'
    repoURL: 'https://github.com/signalfx/splunk-otel-collector-chart'
    # targetRevision: '0.43.2'
    chart: splunk-otel-collector
    helm: 
      parameters:
        - name: logsCollection.containers.excludePaths
          value: '[{{ $i := split "," (fromConfigMap "wookie-policies" "test-templates" "lOut") }}{{- range $bits := $i }} "{{ $bits | trim }}" {{- end }}]'