---
apiVersion: v1
data:
  apiUrl: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}' 
  clusterName: '{{ $n := split "-" (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}{{ $n._0 }}'
kind: ConfigMap
metadata:
  name: test-templates
  namespace: wookie-policies