apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - google:
        clientID: >-
          35776496954-t09ldpfqtsdcmeo29momtfs6inmelcbi.apps.googleusercontent.com
        clientSecret:
          name: goog-auth
        hostedDomain: redhat.com
      mappingMethod: claim
      name: goog-auth
      type: Google
