
---
apiVersion: v1
data:
  loadBalancerSourceRanges: '{{ $i := split "," (fromConfigMap "wookie-policies" "test-templates" "lOut") }}[ {{- range $bits := $i }} {{ \"$bits\" }} {{- end }} ]'
  
kind: ConfigMap
metadata:
  name: range-test
  namespace: wookie-policies

