apiVersion: v1
kind: Service
metadata:
  name: list-tester
  namespace: wookie-policies
spec:
  loadBalancerSourceRanges: '{{ $i := split "," (fromConfigMap "wookie-policies" "test-templates" "lOut") }}[{{- range $bits := $i }} {{ "$bits" }} {{- end }}]'
