apiVersion: v1
kind: Service
metadata:
  name: list-tester
  namespace: wookie-policies
  labels:
    loadBalancerSourceRanges: '{{ $i := split "," (fromConfigMap "wookie-policies" "test-templates" "lOut") }}[{{ range $bits := $i }}{{ $bits }}]{{ end }}''
spec:
  # loadBalancerSourceRanges: '{{ fromConfigMap "wookie-policies" "test-templates" "lOut" | list }}'