apiVersion: v1
kind: Service
metadata:
  name: list-tester
  namespace: wookie-policies
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  # loadBalancerSourceRanges: '{{ $i := split "," (fromConfigMap "wookie-policies" "test-templates" "lOut") }}[ {{- range $bits := $i }} "{{ $bits }}" {{- end }} ]'
  loadBalancerSourceRanges: '[{{ fromConfigMap "wookie-policies" "test-templates" "lOut" }}]'
  type: LoadBalancer