---
apiVersion: v1
kind: Secret
metadata:
    name: argocd-notifications-secret
data:
  bry-general-teams-url: aHR0cHM6Ly9yZWRoYXQwLndlYmhvb2sub2ZmaWNlLmNvbS93ZWJob29rYjIvMDNkZDI5MzYtODU0Yi00M2QzLTkyNzItZDBiNTcxOTljOTZjQDY0ZGM2OWU0LWQwODMtNDlmYy05NTY5LWViZWNlMWRkMTQwOC9JbmNvbWluZ1dlYmhvb2svMmE2MGNjODIzNmZhNGZiZmE0NzZkYTE3OWNhMjNiYmQvNTFmNjg5Y2YtMGEwMy00NjEyLTkwMjEtYmJlMTBhMjdlMzdk
