apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: ""
  labels:
    app: acm-sample-policies
    app.kubernetes.io/part-of: acm-sample-policies
    apps.open-cluster-management.io/reconcile-rate: medium
  name: acm-sample-policies
  namespace: dmte-acm-samples
spec:
  channel: dmte-acm-samples/acm-sample-policies
  placement:
    placementRef:
      kind: PlacementRule
      name: hub-only
