---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-generator
policyDefaults:
  namespace: dmte-acm-samples
  remediationAction: enforce
  policySets:
    - operators
placementBindingDefaults:
  name: "operators-binding"

policies:
  - name: gitops-operator
    remediationAction: enforce
    namespaceSelector:
      matchLabels:
        app.host: argocd
      exclude: 
        - kube-*
        - default
    manifests:
      - path: gitops/
        complianceType: musthave

  - name: gitops-operator-status
    remediationAction: inform
    namespaceSelector:
      matchLabels:
        app.host: argocd
      exclude: 
        - kube-*
        - default
    manifests:
      - path: gitops/health/
        complianceType: musthave


  - name: sysdig-operator
    remediationAction: enforce
    namespaceSelector:
      matchLabels:
        app.host: sysdig
      exclude: 
        - kube-*
        - default
    manifests:
      - path: sysdig/
        complianceType: musthave

  - name: sysdig-operator-status
    remediationAction: inform
    namespaceSelector:
      matchLabels:
        app.host: sysdig
      exclude: 
        - kube-*
        - default
    manifests:
      - path: sysdig/health/
        complianceType: musthave
policySets:
  - name: operators
    placement:
      placementRuleName: "hub-only"
