---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-generator
policyDefaults:
  namespace: dmte-acm-samples
  remediationAction: enforce
  policySets:
    - argocd-helm
placementBindingDefaults:
  name: "argocd-helm-binding"

policies:
  - name: reloader-helm
    remediationAction: enforce
    manifests:
      - path: reloader/
        complianceType: musthave

  - name: reloader-helm-status
    remediationAction: inform
    manifests:
      - path: reloader/health/
        complianceType: musthave


policySets:
  - name: argocd-helm
    placement:
      placementRuleName: "hub-only"
