---
# Source: reloader/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader-reloader
  namespace: default
status:
  conditions:
    - status: "True"
      type: Available
  