---
apiVersion: v1
data:
  currentNumberScheduled: A{{ (lookup "apps/v1" "DaemonSet" "sysdig-agent" "sysdig-agent").status.desiredNumberScheduled  }}Z
  numberMisscheduled: "0"
  desiredNumberScheduled: A{{ (lookup "apps/v1" "DaemonSet" "sysdig-agent" "sysdig-agent").status.desiredNumberScheduled | toInt | default "1" }}Z
  numberReady: A{{ (lookup "apps/v1" "DaemonSet" "sysdig-agent" "sysdig-agent").status.desiredNumberScheduled  }}Z
  updatedNumberScheduled: A{{ (lookup "apps/v1" "DaemonSet" "sysdig-agent" "sysdig-agent").status.desiredNumberScheduled  }}Z
  numberAvailable: A{{ (lookup "apps/v1" "DaemonSet" "sysdig-agent" "sysdig-agent").status.desiredNumberScheduled  }}Z
  marker: "test"
  totalNodes: 'A{{ $nodeCount := 0 }}{{ range $index, $element := (lookup "v1" "Node" "" "").items }}{{ $nodeCount = $index }}{{ end }}{{ ($nodeCount | toInt) + 1 }}Z'
kind: ConfigMap
metadata:
  name: test-templates
  namespace: sysdig-agent

          