kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: sysdig-agent
  namespace: sysdig-agent
  labels:
    app: sysdig-agent
    app.kubernetes.io/instance: sysdig-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sysdig
    app.kubernetes.io/version: 12.9.0
    helm.sh/chart: sysdig-1.15.48
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: sysdig-agent
      app.kubernetes.io/name: sysdig
  template:
    metadata:
      name: sysdig-agent
      labels:
        app: sysdig-agent
        app.kubernetes.io/instance: sysdig-agent
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sysdig
        app.kubernetes.io/version: 12.9.0
        helm.sh/chart: sysdig-1.15.48
    spec:
      restartPolicy: Always
      initContainers:
        - name: sysdig-agent-kmodule
          image: 'quay.io/sysdig/agent-kmodule:12.9.0'
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: '1'
              memory: 348Mi
          volumeMounts:
            - name: modprobe-d
              readOnly: true
              mountPath: /etc/modprobe.d
            - name: boot-vol
              readOnly: true
              mountPath: /host/boot
            - name: modules-vol
              readOnly: true
              mountPath: /host/lib/modules
            - name: usr-vol
              readOnly: true
              mountPath: /host/usr
            - name: etc-vol
              readOnly: true
              mountPath: /host/etc
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: true
            runAsUser: 0
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
      serviceAccountName: sysdig-agent
      hostPID: true
      schedulerName: default-scheduler
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                      - s390x
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                      - s390x
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
      terminationGracePeriodSeconds: 5
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 1Gi
          readinessProbe:
            exec:
              command:
                - test
                - '-e'
                - /opt/draios/logs/running
            initialDelaySeconds: 90
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: sysdig
          env:
            - name: K8S_NODE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: true
            runAsUser: 0
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: etc-vol
              readOnly: true
              mountPath: /host/etc
            - name: dev-vol
              mountPath: /host/dev
            - name: proc-vol
              readOnly: true
              mountPath: /host/proc
            - name: run-vol
              mountPath: /host/run
            - name: varrun-vol
              mountPath: /host/var/run
            - name: dshm
              mountPath: /dev/shm
            - name: sysdig-agent-config
              mountPath: /opt/draios/etc/kubernetes/config
            - name: sysdig-agent-secrets
              mountPath: /opt/draios/etc/kubernetes/secrets
            - name: podinfo
              mountPath: /etc/podinfo
          terminationMessagePolicy: File
          image: 'quay.io/bjarvis/versioned-hello'
      serviceAccount: sysdig-agent
      volumes:
        - name: modprobe-d
          hostPath:
            path: /etc/modprobe.d
            type: ''
        - name: dshm
          emptyDir:
            medium: Memory
        - name: etc-vol
          hostPath:
            path: /etc
            type: ''
        - name: dev-vol
          hostPath:
            path: /dev
            type: ''
        - name: proc-vol
          hostPath:
            path: /proc
            type: ''
        - name: boot-vol
          hostPath:
            path: /boot
            type: ''
        - name: modules-vol
          hostPath:
            path: /lib/modules
            type: ''
        - name: usr-vol
          hostPath:
            path: /usr
            type: ''
        - name: run-vol
          hostPath:
            path: /run
            type: ''
        - name: varrun-vol
          hostPath:
            path: /var/run
            type: ''
        - name: sysdig-agent-config
          configMap:
            name: sysdig-agent
            defaultMode: 420
            optional: true
        - name: sysdig-agent-secrets
          secret:
            secretName: sysdig-agent
            defaultMode: 420
        - name: podinfo
          downwardAPI:
            items:
              - path: namespace
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
              - path: name
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            defaultMode: 420
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10